#!/system/bin/sh
#
# Copyright 2014 Matt "Kryten2k35" Booth
# Contact: kryten2k35@ultimarom.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ArchiDroid Hardswap
if [ -f "/system/jflte-gpe/swap_enabled" ]; then
	if [ "$(busybox swapon --help 2>&1 | grep -qi "\-p pri"; echo $?)" -eq 0 ]; then
		HSEXTRA="-p 10"
	fi
	mount -o remount,rw /cache
	if [ -f "/cache/Swapfile.swp" ]; then
		echo "INFO: Found swap file in /cache directory, $(busybox du -mh "/cache/Swapfile.swp" | cut -f1)"
		busybox swapon $HSEXTRA "/cache/Swapfile.swp" # Yes, we must break on spaces in this case
	else
		echo "INFO: Swap file not found in the /cache directory, but is supposed to be enabled. Recreating"
		SWAP_AMOUNT=$(cat /system/jflte-gpe/swap_enabled)
		echo "Creating swap file with $SWAP_AMOUNT size"
		dd if=/dev/zero of="/cache/Swapfile.swp" bs=1048576 count="$SWAP_AMOUNT"
		mkswap "/cache/Swapfile.swp"
		chown root:root "/cache/Swapfile.swp" # We don't want to create
		chmod 0600 "/cache/Swapfile.swp" # A potential security risk
		busybox swapon $HSEXTRA "/cache/Swapfile.swp" # Yes, we must break on spaces in this case
	fi
fi