#!/bin/bash

echo "Select to either BUILD the ROM, or just the modified apps/jars"
select build in "build" "apps"; do
    case $build in
        build ) ./tools/build_linux; break;;
        apps )  ./tools/compile_apps_linux; break;;
    esac
done