#!/system/bin/sh
#
# Copyright 2014 Matt "Kryten2k35" Booth
# Contact: kryten2k35@ultimarom.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Some people have an issue with tethering. 
# Running this code on the first boot means after their first reboot, everything should be fine

CHECKPART=/system/jflte-gpe/tethering_check
CHECK=$(cat /system/jflte-gpe/tethering_check)

if [ ! -f "$CHECKPART" ]; then
	echo "$CHECKPART does not exist. Creating and setting tethering_dun_required to 0"
	settings put global tether_dun_required 0
	sysrw
	echo "Creating CHECKPART"
	settings get global tether_dun_required &> "$CHECKPART"
	sysro
else
	if [[ "$CHECK" != 0 || "$CHECK" == "null" ]]; then
		echo "$CHECKPART exists, but result is not 0, or is null. Creating and setting tethering_dun_required to 0"
		settings put global tether_dun_required 0
		sysrw
		echo "Creating CHECKPART"
		settings get global tether_dun_required &> "$CHECKPART"
		sysro
	fi 
fi
exit 0
