#!/system/bin/sh
#
# Copyright 2014 MAtt "Kryten2k35" Booth
# Contact: kryten2k35@ultimarom.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Some people have an issue with tethering. 
# Running this code on the first boot means after their first reboot, everything should be fine
CHECKPART=/data/tethering_check
DB="/data/data/com.android.providers.settings/databases/settings.db"

if [ ! -e "$CHECKPART" ]; then
	sqlite3 "$DB" "INSERT INTO global VALUES (null, 'tether_dun_required','0');"
	touch "$CHECKPART"
	echo "This file is here to ensure the tethering script doesn't run on every boot. Please leave alone." >> "$CHECKPART"
	echo " " >> "$CHECKPART"
	sqlite3 "DB" "SELECT * FROM global WHERE name='tether_dun_required';" >> "$CHECKPART"
fi
exit 0
