#!/system/bin/sh
#
# Copyright 2014 Matt "Kryten2k35" Booth
# Contact: kryten2k35@ultimarom.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Disable Ambient Display for first boot.

if [ ! -f /system/jflte-gpe/doze_runonce ]; then
	sysrw
	touch /system/jflte-gpe/doze_runonce
	sysro
	settings put secure doze_enabled 0
fi

exit 0
