#!/bin/bash

APKTOOL=../../tools/apktool
SYSTEM=../../system

cd mods

if [ -d framework ]; then
	cd framework
	for f in *
	do
		"$APKTOOL" b -c "$f"
		cp "$f"/dist/"$f" "$SYSTEM"/framework/"$f"
		rm -rf "$f/dist" "$f/build"
	done
	cd ..
fi

../tools/apktool if ../system/framework/framework-res.apk

if [ -d app ]; then
	cd app
	for f in *
	do
		"$APKTOOL" b -c "$f"
		if [ ! -d "$SYSTEM"/app/"${f%%.*}" ]; then
			mkdir -p "$SYSTEM"/app/"${f%%.*}"
		fi
		cp "$f"/dist/"$f" "$SYSTEM"/app/"${f%%.*}"/"$f"
		rm -rf "$f/dist" "$f/build"
	done
	cd ..
fi

if [ -d priv-app ]; then
	cd priv-app
	for f in *
	do
		"$APKTOOL" b -c "$f"
		if [ ! -d "$SYSTEM"/priv-app/"${f%%.*}" ]; then
			mkdir -p "$SYSTEM"/priv-app/"${f%%.*}"
		fi
		cp "$f"/dist/"$f" "$SYSTEM"/priv-app/"${f%%.*}"/"$f"
		rm -rf "$f/dist" "$f/build"
	done
	cd ..
fi

if [ -d aroma ]; then
	cd aroma
	for f in *
	do
		"$APKTOOL" b -c "$f"
		INSTALL_LOC=$(cat "$f"/install_loc)
		DEST=../../"$INSTALL_LOC"
		cp "$f"/dist/"$f" "$DEST"
		rm -rf "$f/dist" "$f/build"
	done
	cd ..
fi

cd ..
